enum ExceptionCode {

    static let UNKNOWN_EXCEPTION = "UNKNOWN_EXCEPTION"
    static let INITIALIZATION_EXCEPTION = "INITIALIZATION_EXCEPTION"
    static let MISSING_ARGUMENTS = "MISSING_ARGUMENTS"
    static let INVALID_ARGUMENTS = "INVALID_ARGUMENTS"
    static let INSUFFICIENT_PERMISSIONS = "INSUFFICIENT_PERMISSIONS"
    static let SHARED_PREFERENCE_NOT_AVAILABLE = "SHARED_PREFERENCE_NOT_AVAILABLE"
    static let INVALID_IMAGE = "INVALID_IMAGE"
    static let CLASS_NOT_FOUND = "CLASS_NOT_FOUND"
    static let BACKGROUND_EXECUTION_EXCEPTION = "BACKGROUND_EXECUTION_EXCEPTION"
    static let NOTIFICATION_THREAD_EXCEPTION = "NOTIFICATION_THREAD_EXCEPTION"
    static let EVENT_EXCEPTION = "EVENT_EXCEPTION"
}