package me.carda.awesome_notifications.awesome_notifications_core.exceptions;

public interface ExceptionCode {

    String UNKNOWN_EXCEPTION = "UNKNOWN_EXCEPTION";
    String INITIALIZATION_EXCEPTION = "INITIALIZATION_EXCEPTION";
    String MISSING_ARGUMENTS = "MISSING_ARGUMENTS";
    String INVALID_ARGUMENTS = "INVALID_ARGUMENTS";
    String INSUFFICIENT_PERMISSIONS = "INSUFFICIENT_PERMISSIONS";
    String SHARED_PREFERENCE_NOT_AVAILABLE = "SHARED_PREFERENCE_NOT_AVAILABLE";
    String INVALID_IMAGE = "INVALID_IMAGE";
    String CLASS_NOT_FOUND = "CLASS_NOT_FOUND";
    String BACKGROUND_EXECUTION_EXCEPTION = "BACKGROUND_EXECUTION_EXCEPTION";
    String NOTIFICATION_THREAD_EXCEPTION = "NOTIFICATION_THREAD_EXCEPTION";
    String EVENT_EXCEPTION = "EVENT_EXCEPTION";

}
