public enum ExceptionCode {
    
    public static let CODE_MISSING_METHOD = "MISSING_METHOD"
    public static let CODE_UNKNOWN_EXCEPTION = "UNKNOWN_EXCEPTION"
    public static let CODE_INITIALIZATION_EXCEPTION = "INITIALIZATION_EXCEPTION"
    public static let CODE_MISSING_ARGUMENTS = "MISSING_ARGUMENTS"
    public static let CODE_INVALID_ARGUMENTS = "INVALID_ARGUMENTS"
    public static let CODE_INSUFFICIENT_PERMISSIONS = "INSUFFICIENT_PERMISSIONS"
    public static let CODE_SHARED_PREFERENCES_NOT_AVAILABLE = "SHARED_PREFERENCES_NOT_AVAILABLE"
    public static let CODE_INVALID_IMAGE = "INVALID_IMAGE"
    public static let CODE_CLASS_NOT_FOUND = "CLASS_NOT_FOUND"
    public static let CODE_BACKGROUND_EXECUTION_EXCEPTION = "BACKGROUND_EXECUTION_EXCEPTION"
    public static let CODE_NOTIFICATION_THREAD_EXCEPTION = "NOTIFICATION_THREAD_EXCEPTION"
    public static let CODE_PAGE_NOT_FOUND = "PAGE_NOT_FOUND"
    public static let CODE_EVENT_EXCEPTION = "EVENT_EXCEPTION"

    public static let DETAILED_MISSING_METHOD = "missingMethod"
    public static let DETAILED_UNEXPECTED_ERROR = "unexpectedError"
    public static let DETAILED_REQUIRED_ARGUMENTS = "arguments.required"
    public static let DETAILED_CLASS_NOT_FOUND = "class.notFound"
    public static let DETAILED_INVALID_ARGUMENTS = "arguments.invalid"
    public static let DETAILED_PAGE_NOT_FOUND = "pageNotFound"
    public static let DETAILED_INITIALIZATION_FAILED = "initialization"
    public static let DETAILED_SHARED_PREFERENCES = "sharedPreferences"
    public static let DETAILED_INSUFFICIENT_PERMISSIONS = "insufficientPermissions"
    public static let DETAILED_INSUFFICIENT_REQUIREMENTS = "insufficientRequirements"
}
