package me.carda.awesome_notifications.core.exceptions;

public interface ExceptionCode {

    String CODE_UNKNOWN_EXCEPTION = "UNKNOWN_EXCEPTION";
    String CODE_INITIALIZATION_EXCEPTION = "INITIALIZATION_EXCEPTION";
    String CODE_MISSING_ARGUMENTS = "MISSING_ARGUMENTS";
    String CODE_INVALID_ARGUMENTS = "INVALID_ARGUMENTS";
    String CODE_INSUFFICIENT_PERMISSIONS = "INSUFFICIENT_PERMISSIONS";
    String CODE_SHARED_PREFERENCES_NOT_AVAILABLE = "SHARED_PREFERENCES_NOT_AVAILABLE";
    String CODE_INVALID_IMAGE = "INVALID_IMAGE";
    String CODE_CLASS_NOT_FOUND = "CLASS_NOT_FOUND";
    String CODE_BACKGROUND_EXECUTION_EXCEPTION = "BACKGROUND_EXECUTION_EXCEPTION";
    String CODE_NOTIFICATION_THREAD_EXCEPTION = "NOTIFICATION_THREAD_EXCEPTION";
    String CODE_PAGE_NOT_FOUND = "PAGE_NOT_FOUND";
    String CODE_EVENT_EXCEPTION = "EVENT_EXCEPTION";


    String DETAILED_UNEXPECTED_ERROR = "unexpectedError";
    String DETAILED_REQUIRED_ARGUMENTS = "arguments.required";
    String DETAILED_CLASS_NOT_FOUND = "class.notFound";
    String DETAILED_INVALID_ARGUMENTS = "arguments.invalid";
    String DETAILED_PAGE_NOT_FOUND = "pageNotFound";
    String DETAILED_INITIALIZATION_FAILED = "initialization";
    String DETAILED_SHARED_PREFERENCES = "sharedPreferences";
    String DETAILED_INSUFFICIENT_PERMISSIONS = "insufficientPermissions";
    String DETAILED_INSUFFICIENT_REQUIREMENTS = "insufficientRequirements";
}